import { UserRole, NavItem } from '@/shared/types';

export const NAVIGATION: Record<UserRole, NavItem[]> = {
  rahbar: [
    { title: 'nav.dashboard', href: '/rahbar', icon: 'LayoutDashboard' },
    { title: 'nav.projects', href: '/rahbar/projects', icon: 'Building2' },
    { title: 'nav.finance', href: '/rahbar/finance', icon: 'DollarSign' },
    { title: 'nav.norms', href: '/rahbar/norms', icon: 'ShieldAlert' },
    { title: 'nav.auctions', href: '/rahbar/auctions', icon: 'Gavel' },
    { title: 'nav.workers', href: '/rahbar/workers', icon: 'Users' },
    { title: 'nav.warehouse', href: '/rahbar/warehouse', icon: 'Warehouse' },
    { title: 'nav.suppliers', href: '/rahbar/suppliers', icon: 'Truck' },
    { title: 'nav.photos', href: '/rahbar/photos', icon: 'Camera' },
    { title: 'nav.reports', href: '/rahbar/reports', icon: 'FileText' },
    { title: 'nav.ratings', href: '/rahbar/ratings', icon: 'Star' },
    { title: 'nav.notifications', href: '/rahbar/notifications', icon: 'Bell' },
  ],
  prorab: [
    { title: 'nav.dashboard', href: '/prorab', icon: 'LayoutDashboard' },
    { title: 'nav.tasks', href: '/prorab/tasks', icon: 'CheckSquare' },
    { title: 'nav.workers', href: '/prorab/workers', icon: 'Users' },
    { title: 'nav.materials', href: '/prorab/materials', icon: 'Package' },
    { title: 'nav.reports', href: '/prorab/reports', icon: 'FileText' },
    { title: 'nav.photos', href: '/prorab/photos', icon: 'Camera' },
    { title: 'nav.auctions', href: '/prorab/auctions', icon: 'Gavel' },
    { title: 'nav.workVolume', href: '/prorab/work-volume', icon: 'BarChart3' },
    { title: 'nav.notifications', href: '/prorab/notifications', icon: 'Bell' },
  ],
  ombor: [
    { title: 'nav.dashboard', href: '/ombor', icon: 'LayoutDashboard' },
    { title: 'nav.materials', href: '/ombor/materials', icon: 'Package' },
    { title: 'nav.incoming', href: '/ombor/incoming', icon: 'ArrowDownToLine' },
    { title: 'nav.outgoing', href: '/ombor/outgoing', icon: 'ArrowUpFromLine' },
    { title: 'nav.requests', href: '/ombor/requests', icon: 'ClipboardList' },
    { title: 'nav.inventoryCheck', href: '/ombor/inventory-check', icon: 'ClipboardCheck' },
    { title: 'nav.receipts', href: '/ombor/receipts', icon: 'Receipt' },
    { title: 'nav.deliveries', href: '/ombor/deliveries', icon: 'Truck' },
    { title: 'nav.lowStock', href: '/ombor/low-stock', icon: 'AlertTriangle' },
    { title: 'nav.notifications', href: '/ombor/notifications', icon: 'Bell' },
  ],
  admin: [
    { title: 'nav.dashboard', href: '/admin', icon: 'LayoutDashboard' },
    { title: 'nav.attendance', href: '/admin/attendance', icon: 'CalendarCheck' },
    { title: 'nav.tasks', href: '/admin/tasks', icon: 'CheckSquare' },
    { title: 'nav.issues', href: '/admin/issues', icon: 'AlertOctagon' },
    { title: 'nav.activity', href: '/admin/activity', icon: 'Activity' },
    { title: 'nav.users', href: '/admin/users', icon: 'UserCog' },
    { title: 'nav.reports', href: '/admin/reports', icon: 'FileText' },
    { title: 'nav.notifications', href: '/admin/notifications', icon: 'Bell' },
  ],
};
