import { UserRole, NavItem } from '@/shared/types';

export const NAVIGATION: Record<UserRole, NavItem[]> = {
  rahbar: [
    { title: 'Bosh sahifa', href: '/rahbar', icon: 'LayoutDashboard' },
    { title: 'Loyihalar', href: '/rahbar/projects', icon: 'Building2' },
    { title: 'Moliya', href: '/rahbar/finance', icon: 'DollarSign' },
    { title: 'Normativ nazorat', href: '/rahbar/norms', icon: 'ShieldAlert' },
    { title: 'Auktsionlar', href: '/rahbar/auctions', icon: 'Gavel' },
    { title: 'Ishchilar', href: '/rahbar/workers', icon: 'Users' },
    { title: 'Ombor', href: '/rahbar/warehouse', icon: 'Warehouse' },
    { title: 'Yetkazib beruvchilar', href: '/rahbar/suppliers', icon: 'Truck' },
    { title: 'Rasmlar', href: '/rahbar/photos', icon: 'Camera' },
    { title: 'Hisobotlar', href: '/rahbar/reports', icon: 'FileText' },
    { title: 'Reytinglar', href: '/rahbar/ratings', icon: 'Star' },
    { title: 'Bildirishnomalar', href: '/rahbar/notifications', icon: 'Bell' },
  ],
  prorab: [
    { title: 'Bosh sahifa', href: '/prorab', icon: 'LayoutDashboard' },
    { title: 'Vazifalar', href: '/prorab/tasks', icon: 'CheckSquare' },
    { title: 'Ishchilar', href: '/prorab/workers', icon: 'Users' },
    { title: 'Materiallar', href: '/prorab/materials', icon: 'Package' },
    { title: 'Hisobotlar', href: '/prorab/reports', icon: 'FileText' },
    { title: 'Rasmlar', href: '/prorab/photos', icon: 'Camera' },
    { title: 'Auktsionlar', href: '/prorab/auctions', icon: 'Gavel' },
    { title: 'Ish hajmi', href: '/prorab/work-volume', icon: 'BarChart3' },
    { title: 'Bildirishnomalar', href: '/prorab/notifications', icon: 'Bell' },
  ],
  ombor: [
    { title: 'Bosh sahifa', href: '/ombor', icon: 'LayoutDashboard' },
    { title: 'Materiallar', href: '/ombor/materials', icon: 'Package' },
    { title: 'Kirim', href: '/ombor/incoming', icon: 'ArrowDownToLine' },
    { title: 'Chiqim', href: '/ombor/outgoing', icon: 'ArrowUpFromLine' },
    { title: "So'rovlar", href: '/ombor/requests', icon: 'ClipboardList' },
    { title: 'Inventarizatsiya', href: '/ombor/inventory-check', icon: 'ClipboardCheck' },
    { title: 'Xarid cheklar', href: '/ombor/receipts', icon: 'Receipt' },
    { title: 'Yetkazib berish', href: '/ombor/deliveries', icon: 'Truck' },
    { title: 'Kam qolganlar', href: '/ombor/low-stock', icon: 'AlertTriangle' },
    { title: 'Bildirishnomalar', href: '/ombor/notifications', icon: 'Bell' },
  ],
  admin: [
    { title: 'Bosh sahifa', href: '/admin', icon: 'LayoutDashboard' },
    { title: 'Davomat', href: '/admin/attendance', icon: 'CalendarCheck' },
    { title: 'Vazifalar', href: '/admin/tasks', icon: 'CheckSquare' },
    { title: 'Muammolar', href: '/admin/issues', icon: 'AlertOctagon' },
    { title: 'Faoliyat', href: '/admin/activity', icon: 'Activity' },
    { title: 'Foydalanuvchilar', href: '/admin/users', icon: 'UserCog' },
    { title: 'Hisobotlar', href: '/admin/reports', icon: 'FileText' },
    { title: 'Bildirishnomalar', href: '/admin/notifications', icon: 'Bell' },
  ],
};
